/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BetsRouteImport } from './routes/bets'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SportsEventIdRouteImport } from './routes/sports.$eventId'
import { Route as BetsOpenRouteImport } from './routes/bets.open'
import { Route as BetsHistoryRouteImport } from './routes/bets.history'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppSportsRouteImport } from './routes/app.sports'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminBetsRouteImport } from './routes/admin.bets'
import { Route as AccountBalanceRouteImport } from './routes/account.balance'
import { Route as AppSportsIndexRouteImport } from './routes/app.sports.index'
import { Route as AppSportsEventIdRouteImport } from './routes/app.sports.$eventId'
import { Route as AppBetsOpenRouteImport } from './routes/app.bets.open'
import { Route as AppBetsHistoryRouteImport } from './routes/app.bets.history'
import { Route as AdminOddsImportRouteImport } from './routes/admin.odds.import'
import { Route as AdminEventsEventIdFinishRouteImport } from './routes/admin.events.$eventId.finish'

const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsRoute = BetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SportsEventIdRoute = SportsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => SportsRoute,
} as any)
const BetsOpenRoute = BetsOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => BetsRoute,
} as any)
const BetsHistoryRoute = BetsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BetsRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSportsRoute = AppSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBetsRoute = AdminBetsRouteImport.update({
  id: '/admin/bets',
  path: '/admin/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBalanceRoute = AccountBalanceRouteImport.update({
  id: '/account/balance',
  path: '/account/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSportsIndexRoute = AppSportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSportsRoute,
} as any)
const AppSportsEventIdRoute = AppSportsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppSportsRoute,
} as any)
const AppBetsOpenRoute = AppBetsOpenRouteImport.update({
  id: '/bets/open',
  path: '/bets/open',
  getParentRoute: () => AppRoute,
} as any)
const AppBetsHistoryRoute = AppBetsHistoryRouteImport.update({
  id: '/bets/history',
  path: '/bets/history',
  getParentRoute: () => AppRoute,
} as any)
const AdminOddsImportRoute = AdminOddsImportRouteImport.update({
  id: '/admin/odds/import',
  path: '/admin/odds/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdFinishRoute =
  AdminEventsEventIdFinishRouteImport.update({
    id: '/$eventId/finish',
    path: '/$eventId/finish',
    getParentRoute: () => AdminEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/bets': typeof BetsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sports': typeof SportsRouteWithChildren
  '/account/balance': typeof AccountBalanceRoute
  '/admin/bets': typeof AdminBetsRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/overview': typeof AdminOverviewRoute
  '/app/admin': typeof AppAdminRoute
  '/app/sports': typeof AppSportsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/bets/history': typeof BetsHistoryRoute
  '/bets/open': typeof BetsOpenRoute
  '/sports/$eventId': typeof SportsEventIdRoute
  '/app/': typeof AppIndexRoute
  '/admin/odds/import': typeof AdminOddsImportRoute
  '/app/bets/history': typeof AppBetsHistoryRoute
  '/app/bets/open': typeof AppBetsOpenRoute
  '/app/sports/$eventId': typeof AppSportsEventIdRoute
  '/app/sports/': typeof AppSportsIndexRoute
  '/admin/events/$eventId/finish': typeof AdminEventsEventIdFinishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bets': typeof BetsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sports': typeof SportsRouteWithChildren
  '/account/balance': typeof AccountBalanceRoute
  '/admin/bets': typeof AdminBetsRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/overview': typeof AdminOverviewRoute
  '/app/admin': typeof AppAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/bets/history': typeof BetsHistoryRoute
  '/bets/open': typeof BetsOpenRoute
  '/sports/$eventId': typeof SportsEventIdRoute
  '/app': typeof AppIndexRoute
  '/admin/odds/import': typeof AdminOddsImportRoute
  '/app/bets/history': typeof AppBetsHistoryRoute
  '/app/bets/open': typeof AppBetsOpenRoute
  '/app/sports/$eventId': typeof AppSportsEventIdRoute
  '/app/sports': typeof AppSportsIndexRoute
  '/admin/events/$eventId/finish': typeof AdminEventsEventIdFinishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/bets': typeof BetsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sports': typeof SportsRouteWithChildren
  '/account/balance': typeof AccountBalanceRoute
  '/admin/bets': typeof AdminBetsRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/overview': typeof AdminOverviewRoute
  '/app/admin': typeof AppAdminRoute
  '/app/sports': typeof AppSportsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/bets/history': typeof BetsHistoryRoute
  '/bets/open': typeof BetsOpenRoute
  '/sports/$eventId': typeof SportsEventIdRoute
  '/app/': typeof AppIndexRoute
  '/admin/odds/import': typeof AdminOddsImportRoute
  '/app/bets/history': typeof AppBetsHistoryRoute
  '/app/bets/open': typeof AppBetsOpenRoute
  '/app/sports/$eventId': typeof AppSportsEventIdRoute
  '/app/sports/': typeof AppSportsIndexRoute
  '/admin/events/$eventId/finish': typeof AdminEventsEventIdFinishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bets'
    | '/login'
    | '/register'
    | '/sports'
    | '/account/balance'
    | '/admin/bets'
    | '/admin/events'
    | '/admin/overview'
    | '/app/admin'
    | '/app/sports'
    | '/auth/login'
    | '/auth/register'
    | '/bets/history'
    | '/bets/open'
    | '/sports/$eventId'
    | '/app/'
    | '/admin/odds/import'
    | '/app/bets/history'
    | '/app/bets/open'
    | '/app/sports/$eventId'
    | '/app/sports/'
    | '/admin/events/$eventId/finish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bets'
    | '/login'
    | '/register'
    | '/sports'
    | '/account/balance'
    | '/admin/bets'
    | '/admin/events'
    | '/admin/overview'
    | '/app/admin'
    | '/auth/login'
    | '/auth/register'
    | '/bets/history'
    | '/bets/open'
    | '/sports/$eventId'
    | '/app'
    | '/admin/odds/import'
    | '/app/bets/history'
    | '/app/bets/open'
    | '/app/sports/$eventId'
    | '/app/sports'
    | '/admin/events/$eventId/finish'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bets'
    | '/login'
    | '/register'
    | '/sports'
    | '/account/balance'
    | '/admin/bets'
    | '/admin/events'
    | '/admin/overview'
    | '/app/admin'
    | '/app/sports'
    | '/auth/login'
    | '/auth/register'
    | '/bets/history'
    | '/bets/open'
    | '/sports/$eventId'
    | '/app/'
    | '/admin/odds/import'
    | '/app/bets/history'
    | '/app/bets/open'
    | '/app/sports/$eventId'
    | '/app/sports/'
    | '/admin/events/$eventId/finish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BetsRoute: typeof BetsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SportsRoute: typeof SportsRouteWithChildren
  AccountBalanceRoute: typeof AccountBalanceRoute
  AdminBetsRoute: typeof AdminBetsRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminOverviewRoute: typeof AdminOverviewRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AdminOddsImportRoute: typeof AdminOddsImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets': {
      id: '/bets'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof BetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sports/$eventId': {
      id: '/sports/$eventId'
      path: '/$eventId'
      fullPath: '/sports/$eventId'
      preLoaderRoute: typeof SportsEventIdRouteImport
      parentRoute: typeof SportsRoute
    }
    '/bets/open': {
      id: '/bets/open'
      path: '/open'
      fullPath: '/bets/open'
      preLoaderRoute: typeof BetsOpenRouteImport
      parentRoute: typeof BetsRoute
    }
    '/bets/history': {
      id: '/bets/history'
      path: '/history'
      fullPath: '/bets/history'
      preLoaderRoute: typeof BetsHistoryRouteImport
      parentRoute: typeof BetsRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sports': {
      id: '/app/sports'
      path: '/sports'
      fullPath: '/app/sports'
      preLoaderRoute: typeof AppSportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bets': {
      id: '/admin/bets'
      path: '/admin/bets'
      fullPath: '/admin/bets'
      preLoaderRoute: typeof AdminBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/balance': {
      id: '/account/balance'
      path: '/account/balance'
      fullPath: '/account/balance'
      preLoaderRoute: typeof AccountBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sports/': {
      id: '/app/sports/'
      path: '/'
      fullPath: '/app/sports/'
      preLoaderRoute: typeof AppSportsIndexRouteImport
      parentRoute: typeof AppSportsRoute
    }
    '/app/sports/$eventId': {
      id: '/app/sports/$eventId'
      path: '/$eventId'
      fullPath: '/app/sports/$eventId'
      preLoaderRoute: typeof AppSportsEventIdRouteImport
      parentRoute: typeof AppSportsRoute
    }
    '/app/bets/open': {
      id: '/app/bets/open'
      path: '/bets/open'
      fullPath: '/app/bets/open'
      preLoaderRoute: typeof AppBetsOpenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bets/history': {
      id: '/app/bets/history'
      path: '/bets/history'
      fullPath: '/app/bets/history'
      preLoaderRoute: typeof AppBetsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/odds/import': {
      id: '/admin/odds/import'
      path: '/admin/odds/import'
      fullPath: '/admin/odds/import'
      preLoaderRoute: typeof AdminOddsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/finish': {
      id: '/admin/events/$eventId/finish'
      path: '/$eventId/finish'
      fullPath: '/admin/events/$eventId/finish'
      preLoaderRoute: typeof AdminEventsEventIdFinishRouteImport
      parentRoute: typeof AdminEventsRoute
    }
  }
}

interface AppSportsRouteChildren {
  AppSportsEventIdRoute: typeof AppSportsEventIdRoute
  AppSportsIndexRoute: typeof AppSportsIndexRoute
}

const AppSportsRouteChildren: AppSportsRouteChildren = {
  AppSportsEventIdRoute: AppSportsEventIdRoute,
  AppSportsIndexRoute: AppSportsIndexRoute,
}

const AppSportsRouteWithChildren = AppSportsRoute._addFileChildren(
  AppSportsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppSportsRoute: typeof AppSportsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppBetsHistoryRoute: typeof AppBetsHistoryRoute
  AppBetsOpenRoute: typeof AppBetsOpenRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppSportsRoute: AppSportsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppBetsHistoryRoute: AppBetsHistoryRoute,
  AppBetsOpenRoute: AppBetsOpenRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BetsRouteChildren {
  BetsHistoryRoute: typeof BetsHistoryRoute
  BetsOpenRoute: typeof BetsOpenRoute
}

const BetsRouteChildren: BetsRouteChildren = {
  BetsHistoryRoute: BetsHistoryRoute,
  BetsOpenRoute: BetsOpenRoute,
}

const BetsRouteWithChildren = BetsRoute._addFileChildren(BetsRouteChildren)

interface SportsRouteChildren {
  SportsEventIdRoute: typeof SportsEventIdRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsEventIdRoute: SportsEventIdRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

interface AdminEventsRouteChildren {
  AdminEventsEventIdFinishRoute: typeof AdminEventsEventIdFinishRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsEventIdFinishRoute: AdminEventsEventIdFinishRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BetsRoute: BetsRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SportsRoute: SportsRouteWithChildren,
  AccountBalanceRoute: AccountBalanceRoute,
  AdminBetsRoute: AdminBetsRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminOverviewRoute: AdminOverviewRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AdminOddsImportRoute: AdminOddsImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
